apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "synchain.fullname" . }}
  labels:
    app: {{ template "synchain.name" . }}
    chart: {{ template "synchain.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.configurationFiles | indent 2 }}
