apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "bitcoind.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bitcoind.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.configurationFiles }}
      initContainers:
        - name: copy-bitcoind-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/* /syn/config/']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /syn/config/
      {{- end }}
      containers:
        - name: {{ template "bitcoind.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.runCommand }}
          command:
            {{  range .Values.runCommand }}
            - {{ . }}
            {{ end }}
          {{- end }}
          {{- if .Values.arguments }}
          args:
          {{- range .Values.arguments }}
            - {{ . }}
          {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpcPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
            - name: testnet
              containerPort: {{ .Values.service.testnetPort }}
            - name: testnetp2pport
              containerPort: {{ .Values.service.testnetP2pPort }}
          volumeMounts:
            - name: data
              mountPath: /syn
            {{- if .Values.configurationFiles }}
            - name: config
              mountPath: /syn/config/
            {{- end }}
      volumes:
        {{- if .Values.configurationFiles }}
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: {{ template "bitcoind.fullname" . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "bitcoind.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
