apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "bitcoind.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bitcoind.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.configurationFiles }}
      initContainers:
        - name: make-data-dir
          image: busybox
          # todo: needs to be bumped down
          command: ['sh', '-c', 'mkdir -m 7777 -p /syn/data']
          volumeMounts:
            - name: data
              mountPath: /syn
        - name: copy-synapse-config
          image: busybox
          # todo consider allowing soft failure on this copy.
          command: ['sh', '-c', 'cp -v /configmap/* /config/ && cp -n /configmap/priv_validator_state.json /syn/data/priv_validator_state.json']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /config/
            - name: data
              mountPath: /syn
      {{- end }}
        - name: debug-synapse-config
          image: busybox
          # todo consider allowing soft failure on this copy.
          command: ['sh', '-c', 'cd /syn && echo "syn" && ls && cd /syn/config && echo "config" && ls && cd /syn/data && echo "data" && ls']
          volumeMounts:
            - name: data
              mountPath: /syn
            {{- if .Values.configurationFiles }}
            - name: config
              mountPath: /syn/config/
            {{- end }}
      containers:
        - name: {{ template "bitcoind.fullname" . }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.runCommand }}
          command:
            {{  range .Values.runCommand }}
            - {{ . }}
            {{ end }}
          {{- end }}
          {{- if .Values.arguments }}
          args:
          {{- range .Values.arguments }}
            - {{ . }}
          {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: api
              containerPort: {{ .Values.service.apiPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
            - name: rpc
              containerPort: {{ .Values.service.rpc }}
            - name: rosetta
              containerPort: {{ .Values.service.rosetta }}
            - name: grpc
              containerPort: {{ .Values.service.grpc }}
          volumeMounts:
            - name: data
              mountPath: /syn
            {{- if .Values.configurationFiles }}
            - name: config
              mountPath: /syn/config/
            {{- end }}
      volumes:
        {{- if .Values.configurationFiles }}
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: {{ template "bitcoind.fullname" . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "bitcoind.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
