apiVersion: v1
kind: Secret
metadata:
  name: {{ include "syn-node.fullname" . }}-keys
  namespace: {{ .Release.Namespace }}
  app: {{ template "synchain.name" . }}
  chart: {{ template "synchain.chart" . }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: "Opaque"
data:
{{ toYaml .Values.secretFiles | indent 2 }}
