apiVersion: v1
kind: Service
metadata:
  name: {{ template "synchain.fullname" . }}
  labels:
    app: {{ template "synchain.name" . }}
    chart: {{ template "synchain.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: rosetta
      port: {{ .Values.service.rosettaPort }}
      targetPort: rosetta
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
  selector:
    app: {{ template "synchain.name" . }}
    release: {{ .Release.Name }}
